services:
  Dbp\Relay\MonoConnectorCampusonlineBundle\Service\TuitionFeeService:
    autowire: true
    autoconfigure: true
    public: true
    calls:
      - setAuditLogger: ['@monolog.logger.dbp_relay_mono_audit']

  Dbp\Relay\MonoConnectorCampusonlineBundle\Service\HealthCheck:
    autowire: true
    autoconfigure: true
