services:
  Dbp\Relay\MonoConnectorCampusonlineBundle\Service\LdapService:
    autowire: true
    autoconfigure: true

  Dbp\Relay\MonoConnectorCampusonlineBundle\Service\TuitionFeeService:
    autowire: true
    autoconfigure: true
    public: true
    tags:
      - { name: monolog.logger, channel: 'dbp_relay_mono_audit' }

  Dbp\Relay\MonoConnectorCampusonlineBundle\Service\HealthCheck:
    autowire: true
    autoconfigure: true
